# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# project.py
# Created on: 2016-03-04 08:05:05.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
house = "house"
house_Project = "C:\\Users\\poshan\\Documents\\ArcGIS\\Default.gdb\\house_Project"

# Process: Project
arcpy.Project_management(house, house_Project, "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]", "mutmToWgs", "PROJCS['Everest_Adj_1937_Transverse_Mercator',GEOGCS['GCS_Everest_Adj_1937',DATUM['D_Everest_Adj_1937',SPHEROID['Everest_Adjustment_1937',6377276.345,300.8017]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',84.0],PARAMETER['Scale_Factor',0.9999],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]]", "NO_PRESERVE_SHAPE", "")

