# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# definecustom.py
# Created on: 2016-03-04 08:02:10.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
Output_Geographic_Coordinate_System = "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]"

# Process: Create Custom Geographic Transformation
arcpy.CreateCustomGeoTransformation_management("mutmToWgs", "PROJCS['Everest_Adj_1937_Transverse_Mercator',GEOGCS['GCS_Everest_Adj_1937',DATUM['D_Everest_Adj_1937',SPHEROID['Everest_Adjustment_1937',6377276.345,300.8017]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',84.0],PARAMETER['Scale_Factor',0.9999],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]]", Output_Geographic_Coordinate_System, "GEOGTRAN[METHOD['Molodensky'],PARAMETER['X_Axis_Translation',296.207],PARAMETER['Y_Axis_Translation',737.545],PARAMETER['Z_Axis_Translation',273.001]]")

